### ISSUE TITLE
Module Pre-Release

### ISSUE THREAD

**Issue by Dreamwalker666** [TGates71/sencrypt#1]
I'm not sure how to get a module from this repo you mention http://zppy-repo.mach-hosting.com but I can't find the module.  I understand it's a WIP but I wanted to give it a go.

**Comment by Ron-e** [comment]
It's not on that repo.. but...
First off all: this is **totally on your own risk**! 
Don't do this if you do not know what you're doing..
http://zppy-repo.mach-hosting.com/testing/sencrypt.zpp

**Comment by TGates71** [comment]
I just updated the package in /testing/ with what is currently on GitHub.
So you will need to add the testing repo:
```
zppy repo add zppy-repo.mach-hosting.com/testing
zppy update
zppy install sencrypt
```

**Comment by TGates71** [comment]
Currently the main issue is saving the certificates. Need to get Apache to talk to root and grab/write them to the folders. Once root and apache are working together, I can continue to work on the module.
One suggestion was to have apache create a file that root can read and execute if exists using a cron job which would then grab and write the certificates. But I figured this was a more difficult task for a module since a cron job needs to be created.

**Comment by TGates71** [comment]
More forward progress. Chose a different route for getting certs using PHP. (https://github.com/analogic/lescript) 
Stops in Lescript.php line 264+ (generateCSR function)
```
		// not working
        $domain = reset($domains);
		// not working
        $san = implode(",", array_map(function ($dns) {
            return "DNS:" . $dns;
        }, $domains));
```

**Comment by TGates71** [comment]
UPDATE:
Now installs and activates or deletes certificates for domains and sub domains!
Still need to sort out www. prefix (make a combined cert for both www.domain.tld and domain.tld)
Also need to add certificate revocation to the delete process.

**Comment by TGates71** [comment]
zppy-repo.mach-hosting.com/testing/sencrypt.zpp also updated with current code.

**Comment by TGates71** [comment]
This module has become a core module in Sentora v2.0.0.
